image: conda/miniconda3

stages:
  - lint
  - test
  - build
  - deploy

lint:
  stage: lint
  script:
    - conda install python=3.6 psutil
    - pip install -e .
    - pip install flake8 pep8-naming flake8-docstrings
    - flake8 --config=.flake8 estraces tests setup.py

test:python36:
  stage: test
  script:
    - eval "$(conda shell.bash hook)"
    - conda create -n env-python36 python=3.6 psutil
    - conda activate env-python36
    - python setup.py test -v

test:python37:
  stage: test
  script:
    - eval "$(conda shell.bash hook)"
    - conda create -n env-python37 python=3.7 psutil
    - conda activate env-python37
    - python setup.py test -v

test:python38:
  stage: test
  script:
    - eval "$(conda shell.bash hook)"
    - conda create -n env-python38 python=3.8 psutil
    - conda activate env-python38
    - python setup.py test -v

build:pypi:
  stage: build
  script:
    - conda install python=3.6
    - pip install -U pip setuptools wheel
    - python setup.py sdist bdist_wheel
  only:
    - tags
  artifacts:
    paths:
      - "dist/*"

deploy:pypi:
  stage: deploy
  only:
    - tags
  when: manual
  script:
    - conda install python=3.6
    - pip install -U pip setuptools wheel twine
    - twine upload --repository-url $PYPI_REPOSITORY dist/*  -u $PYPI_USERNAME -p $PYPI_PWD

build:conda:
  stage: build
  script:
    - conda install python=3.6 conda-build conda-verify
    - conda config --add channels $ANACONDA_CHANNEL
    - conda build --output-folder out .recipe
  only:
    - tags
  artifacts:
    paths:
      - "out/*/*.tar.bz2"

deploy:conda:
  stage: deploy
  script:
    - conda config --add channels $ANACONDA_CHANNEL
    - conda install anaconda-client
    - anaconda login --username $ANACONDA_USERNAME --password $ANACONDA_PWD
    - anaconda upload out/noarch/estraces*.tar.bz2
  only:
    - tags
  when: manual
  artifacts:
    paths:
      - "out/*/*.tar.bz2"


pages:
  stage: build
  script:
    - conda install python=3.6 psutil
    - pip install -e .
    - cd docs
    - ./build_doc.sh
  artifacts:
    paths:
    - public
  only:
    - tags
